CREATE TABLE [dbo].[CEPAGE] (
    [CEPAGE_ID]      UNIQUEIDENTIFIER NOT NULL,
    [CEPAGE_NAME]    VARCHAR (50)     NOT NULL,
    [CEPAGE_COLOR]   VARCHAR (50)     NOT NULL,
    [CEPAGE_PERCENT] SMALLINT         NOT NULL,
    PRIMARY KEY CLUSTERED ([CEPAGE_ID] ASC)
);

