CREATE TABLE [dbo].[INGREDIENT] (
    [INGREDIENT_ID] UNIQUEIDENTIFIER NOT NULL,
    [NAME]          VARCHAR (50)     NOT NULL,
    [ID_QUANTITY]   UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_INGREDIENT] PRIMARY KEY CLUSTERED ([INGREDIENT_ID] ASC)
);

