CREATE TABLE [dbo].[QUANTITY] (
    [QUANTITY_ID]    UNIQUEIDENTIFIER NOT NULL,
    [QUANTITY_VALUE] DECIMAL (6, 2)   NOT NULL,
    [QUANTITY_UNIT]  SMALLINT         NOT NULL,
    CONSTRAINT [PK_QUANTITY] PRIMARY KEY CLUSTERED ([QUANTITY_ID] ASC)
);

