CREATE TABLE [dbo].[RECIPE] (
    [RECIPE_ID] UNIQUEIDENTIFIER NOT NULL,
    [NAME]      VARCHAR (50)     NOT NULL,
    [NB_PERSON] SMALLINT         NOT NULL,
    CONSTRAINT [PK_RECIPE] PRIMARY KEY CLUSTERED ([RECIPE_ID] ASC)
);

