CREATE TABLE [dbo].[RECIPE_INGREDIENT] (
    [RECIPE_INGREDIENT_ID] UNIQUEIDENTIFIER NOT NULL,
    [RECIPE_ID]            UNIQUEIDENTIFIER NOT NULL,
    [INGREDIENT_ID]        UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_RECIPE_INGREDIENT] PRIMARY KEY CLUSTERED ([RECIPE_INGREDIENT_ID] ASC)
);

