CREATE TABLE [dbo].[REGION] (
    [REGION_ID]   UNIQUEIDENTIFIER NOT NULL,
    [REGION_NAME] VARCHAR (50)     NOT NULL,
    [REGION_CITY] VARCHAR (50)     NOT NULL,
    PRIMARY KEY CLUSTERED ([REGION_ID] ASC)
);

