CREATE TABLE [dbo].[STEP] (
    [STEP_ID]     UNIQUEIDENTIFIER NOT NULL,
    [DESCRIPTION] VARCHAR (250)    NULL,
    [STEP_ORDER]  SMALLINT         NOT NULL,
    [RECIPE_ID]   UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_STEP] PRIMARY KEY CLUSTERED ([STEP_ID] ASC)
);

