CREATE TABLE [dbo].[WINE_AROME] (
    [WINE_AROME_ID] UNIQUEIDENTIFIER NOT NULL,
    [WINE_ID]       UNIQUEIDENTIFIER NOT NULL,
    [AROME_ID]      UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY CLUSTERED ([WINE_AROME_ID] ASC)
);

