CREATE TABLE [dbo].[WINE_BOTTLE] (
    [WINE_BOTTLE_ID]             UNIQUEIDENTIFIER NOT NULL,
    [WINE_BOTTLE_REFERENCE]      VARCHAR (12)     NULL,
    [WINE_BOTTLE_ENTRY_DATE]     DATETIME         NULL,
    [WINE_BOTTLE_PREDICTED_DATE] DATETIME         NULL,
    [WINE_BOTTLE_EXIT_DATE]      DATETIME         NULL,
    [WINE_BOTTLE_REVIEW]         VARCHAR (500)    NULL,
    [WINE_BOTTLE_STATUS]         SMALLINT         NOT NULL,
    [WINE_CELLAR_ID]             UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([WINE_BOTTLE_ID] ASC)
);

