CREATE TABLE [dbo].[WINE] (
    [WINE_ID]          UNIQUEIDENTIFIER NOT NULL,
    [WINE_NAME]        VARCHAR (50)     NOT NULL,
    [WINE_DESCRIPTION] VARCHAR (250)    NULL,
    [WINE_MILLESIME]   INT              NOT NULL,
    [WINE_COLOR]       SMALLINT         NOT NULL,
    [WINE_APPELATION]  VARCHAR (50)     NOT NULL,
    [WINE_RANKING]     VARCHAR (50)     NOT NULL,
    [QUANTITY_ID]      UNIQUEIDENTIFIER NOT NULL,
    [DOMAIN_ID]        UNIQUEIDENTIFIER NOT NULL,
    [REGION_ID]        UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY CLUSTERED ([WINE_ID] ASC)
);

