CREATE PROCEDURE [dbo].[sp_wine_select]

	@wine_id UNIQUEIDENTIFIER = NULL,
	@name VARCHAR(50) = NULL,
	@millesime INT = NULL,
	@wine_color SMALLINT = NULL,
	@appelation VARCHAR(50) = NULL,
	@ranking VARCHAR(50) = NULL,
	@quantity_id UNIQUEIDENTIFIER = NULL,
	@domain_id UNIQUEIDENTIFIER = NULL,
	@region_id UNIQUEIDENTIFIER = NULL

AS
BEGIN

	SET NOCOUNT ON;	

	IF(@name IS NOT NULL AND @millesime IS NOT NULL AND @wine_color IS NOT NULL AND @appelation IS NOT NULL AND @ranking IS NOT NULL AND @quantity_id IS NOT NULL AND @domain_id IS NOT NULL AND @region_id IS NOT NULL)
		
		SELECT * FROM WINE w (NOLOCK)
		INNER JOIN QUANTITY q (NOLOCK) ON w.QUANTITY_ID = q.QUANTITY_ID
		INNER JOIN DOMAIN d (NOLOCK) ON w.DOMAIN_ID = d.DOMAIN_ID
		INNER JOIN REGION r (NOLOCK) ON w.REGION_ID = r.REGION_ID
		INNER JOIN WINE_CEPAGE wc (NOLOCK) ON w.WINE_ID = wc.WINE_ID
		INNER JOIN CEPAGE c (NOLOCK) ON wc.CEPAGE_ID = c.CEPAGE_ID
		INNER JOIN WINE_AROME wa (NOLOCK) ON w.WINE_ID = wa.WINE_ID
		INNER JOIN AROME a (NOLOCK) ON wa.AROME_ID = a.AROME_ID
		WHERE w.WINE_NAME = @name
			AND w.WINE_MILLESIME = @millesime
			AND w.WINE_COLOR = @wine_color
			AND w.WINE_APPELATION = @appelation
			AND w.WINE_RANKING = @ranking
			AND w.QUANTITY_ID = @quantity_id
			AND w.DOMAIN_ID = @domain_id
			AND w.REGION_ID = @region_id

	ELSE IF(@wine_id IS NOT NULL)
		
		SELECT * FROM WINE w (NOLOCK)
		INNER JOIN QUANTITY q (NOLOCK) ON w.QUANTITY_ID = q.QUANTITY_ID
		INNER JOIN DOMAIN d (NOLOCK) ON w.DOMAIN_ID = d.DOMAIN_ID
		INNER JOIN REGION r (NOLOCK) ON w.REGION_ID = r.REGION_ID
		WHERE w.WINE_ID = @wine_id

	ELSE

		SELECT * FROM WINE w (NOLOCK)
		INNER JOIN QUANTITY q (NOLOCK) ON w.QUANTITY_ID = q.QUANTITY_ID
		INNER JOIN DOMAIN d (NOLOCK) ON w.DOMAIN_ID = d.DOMAIN_ID
		INNER JOIN REGION r (NOLOCK) ON w.REGION_ID = r.REGION_ID

END